[fuiz]
max_slides_count = 100
max_title_length = 200
max_player_count = 1000

[fuiz.multiple_choice]
min_title_length = 0
max_title_length = 200
min_introduce_question = 1
max_introduce_question = 30
min_time_limit = 5
max_time_limit = 240
max_answer_count = 8

[fuiz.corkboard]
id_length = 16
max_alt_length = 200

[fuiz.answer_text]
max_length = 200

[fuiz.bingo]
max_answer_count = 200